FROM python:3.10-slim

WORKDIR /app

# Note the path is relative to the docker-compose.yml location
COPY ./scripts/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./scripts/seed_db.py .

CMD ["python", "seed_db.py"]