version: '3.8'

services:
  # --- INFRASTRUCTURE SERVICES ---
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "3001:3001"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=mrid_admin
      - MINIO_ROOT_PASSWORD=mrid_admin12345
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console UI port
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI port

  # --- APPLICATION SERVICES ---
  simulation_orchestrator:
    build:
      context: ../backend/services/simulation_orchestrator
    ports:
      - "8000:8000"
    volumes:
      # Mount the Docker socket to allow this container to control Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the code for live-reloading during development
      - ../backend/services/simulation_orchestrator/app:/app/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:3001/db
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  postgres_data:
  minio_data: